export const devolute = `From the mouths of those...
English glasnost...
Who use air rifles on their friendly...
Why is the truly skint never ssssss-scotch ridden...
Embrace...negate...
How does...
Devolute...
Man prise the political from anything from a garden...
Metamorphosis...barge...
Eject plane or a loaf...
Euro jazz...devo-land...
English glasnost...
Metro-jazz...
To re-iterate
Indiginous...
Injury list...
Devolute-tionite...
The stinking cast and the stinking east...
In fear of bill...
Three mile quaker pub radius...
Became different person...
The reality of right of portion of forthcoming...
'Tricity and face three years solid for evasion...
Was posessed by the indiginous... Chorltonite natural aversion...
There is also the little matter of shafting somebody while they're working...
Like what you did at Shefield...
Get lost...
Yours sincerely...
Famous face...
Pop star...
Also when are you can't afford a stamp...
And get with food...
Fat-arse...
Which...
It's the gas electric workers and the carpenters...
Is more than I have since end of May...
And the assertion of the letters to press battery better make it better
Tenth...
Goodbye cackhead...
Sincere...
Yours...
Smith...
Faced murderer...
Geriatric...
Like indiginous...
You wanted to know that didn't ya...
English glasnost...
Chorltonite
Why are the truly skint never...
Devoluted...
What would life be without comedy...
How does the political man prise from anyth'...
Music and comedy...
From a garden...
Devolute...
Eject...
What would it be like...
Plague...
Or a loaf...
What would life be like without...

Devolute
And forget to
Reboot the gas boiler
Don't forget to
Listen to
The phone in BBC
Northern

God I thought
I'd regret
Some crocus
God I thought I
Had recruit
Some crocus
The gurning hosts
Were grinning twinkle eyed
Maniac
Rumour host
And all the stuff in your...
Invalid
Devolute
I... on freezin' rot
Strafed by
Days of chance
English glasnost
Its visitation is vibration
I am not
Wrong-able
From the werewolf
And the...
Pseudo jobs
English glasnost
The unutterable
Refrain duplex
In the shrine
Found a photo booth
In... absolute
Devolute
Devolute`;